'use client';

import React, { useState, useEffect } from 'react';
import { useAuth } from '@/context/auth-context';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Loader2, Save, Clock, Info } from 'lucide-react';
import { DaySchedule } from '@/types';

const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

export default function SchedulePage() {
  const { user, updateUser } = useAuth();
  const [isLoading, setIsLoading] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // local state for schedule rows
  const [scheduleList, setScheduleList] = useState<DaySchedule[]>([]);

  useEffect(() => {
    if (user) {
      const userSchedule = user.schedule || [];
      // Pre-populate with all 7 days if any are missing
      const fullSchedule = DAYS_OF_WEEK.map((day) => {
        const existingDay = userSchedule.find(
          (s) => s.day.toLowerCase() === day.toLowerCase()
        );
        return (
          existingDay || {
            day,
            isWorking: false,
            startTime: '09:00',
            endTime: '17:00',
            slotDuration: 30,
          }
        );
      });
      setScheduleList(fullSchedule);
    }
  }, [user]);

  if (!user) return null;

  if (user.role !== 'doctor') {
    return (
      <div className="rounded-2xl bg-destructive/10 border border-destructive/20 p-6 max-w-2xl mx-auto text-center">
        <h2 className="text-xl font-bold text-destructive mb-2">Access Denied</h2>
        <p className="text-muted-foreground">
          Only registered doctors are allowed to configure working schedules.
        </p>
      </div>
    );
  }

  const handleToggle = (index: number) => {
    setScheduleList((prev) =>
      prev.map((item, idx) =>
        idx === index ? { ...item, isWorking: !item.isWorking } : item
      )
    );
  };

  const handleTimeChange = (index: number, field: 'startTime' | 'endTime', value: string) => {
    setScheduleList((prev) =>
      prev.map((item, idx) =>
        idx === index ? { ...item, [field]: value } : item
      )
    );
  };

  const handleDurationChange = (index: number, value: number) => {
    setScheduleList((prev) =>
      prev.map((item, idx) =>
        idx === index ? { ...item, slotDuration: value } : item
      )
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setMessage(null);

    try {
      const response = await api.patch('/users/profile', {
        schedule: scheduleList,
      });
      updateUser(response.data.data);
      setMessage({ type: 'success', text: 'Schedule configured successfully!' });
    } catch (err: any) {
      setMessage({
        type: 'error',
        text: err.response?.data?.message || 'Failed to save schedule settings.',
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-10">
      {/* Title */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Configure Schedule</h1>
        <p className="text-muted-foreground mt-1">
          Define your weekly working days, clinic timings, and appointment slot durations.
        </p>
      </div>

      <div className="flex items-start gap-3 rounded-2xl bg-blue-500/10 border border-blue-500/20 p-4 text-sm text-blue-700 dark:text-blue-400">
        <Info className="h-5 w-5 shrink-0 mt-0.5" />
        <div>
          Patients will book appointments based on the slots generated by these settings. Make sure you define active days and valid time intervals.
        </div>
      </div>

      {message && (
        <div
          className={`rounded-2xl border p-4 text-sm transition-all ${
            message.type === 'success'
              ? 'bg-green-500/10 border-green-500/20 text-green-700 dark:text-green-400'
              : 'bg-destructive/10 border-destructive/20 text-destructive'
          }`}
        >
          {message.text}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="rounded-2xl border border-border bg-card shadow-sm overflow-hidden">
          {/* Table Header (hidden on mobile) */}
          <div className="hidden md:grid grid-cols-12 gap-4 bg-muted/50 p-4 font-semibold text-sm border-b border-border text-muted-foreground">
            <div className="col-span-3">Day of Week</div>
            <div className="col-span-2 text-center">Status</div>
            <div className="col-span-3">Working Hours (Start)</div>
            <div className="col-span-2">Working Hours (End)</div>
            <div className="col-span-2">Duration (mins)</div>
          </div>

          {/* Schedule list */}
          <div className="divide-y divide-border">
            {scheduleList.map((item, index) => (
              <div
                key={item.day}
                className={`grid grid-cols-1 md:grid-cols-12 gap-4 p-4 items-center transition-all ${
                  item.isWorking
                    ? 'bg-primary/5'
                    : 'bg-card opacity-70 hover:opacity-100'
                }`}
              >
                {/* Day label */}
                <div className="col-span-1 md:col-span-3">
                  <span className="font-bold text-base md:text-sm text-foreground">
                    {item.day}
                  </span>
                </div>

                {/* Status Toggle Switch */}
                <div className="col-span-1 md:col-span-2 flex items-center justify-start md:justify-center">
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      className="sr-only peer"
                      checked={item.isWorking}
                      onChange={() => handleToggle(index)}
                    />
                    <div className="w-11 h-6 bg-muted peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-border after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                    <span className="ml-3 text-sm font-medium text-muted-foreground md:hidden">
                      {item.isWorking ? 'Working' : 'Off-day'}
                    </span>
                  </label>
                </div>

                {/* Start Time */}
                <div className="col-span-1 md:col-span-3 space-y-1 md:space-y-0">
                  <span className="text-xs text-muted-foreground md:hidden block">Start Time</span>
                  <input
                    type="time"
                    value={item.startTime}
                    onChange={(e) => handleTimeChange(index, 'startTime', e.target.value)}
                    disabled={!item.isWorking}
                    className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:bg-muted/50 disabled:opacity-50"
                  />
                </div>

                {/* End Time */}
                <div className="col-span-1 md:col-span-2 space-y-1 md:space-y-0">
                  <span className="text-xs text-muted-foreground md:hidden block">End Time</span>
                  <input
                    type="time"
                    value={item.endTime}
                    onChange={(e) => handleTimeChange(index, 'endTime', e.target.value)}
                    disabled={!item.isWorking}
                    className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:bg-muted/50 disabled:opacity-50"
                  />
                </div>

                {/* Duration */}
                <div className="col-span-1 md:col-span-2 space-y-1 md:space-y-0">
                  <span className="text-xs text-muted-foreground md:hidden block">Slot Duration</span>
                  <select
                    value={item.slotDuration}
                    onChange={(e) => handleDurationChange(index, Number(e.target.value))}
                    disabled={!item.isWorking}
                    className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:bg-muted/50 disabled:opacity-50"
                  >
                    {[15, 20, 30, 45, 60, 90, 120].map((mins) => (
                      <option key={mins} value={mins}>
                        {mins}m
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="flex justify-end">
          <Button
            type="submit"
            variant="gradient"
            size="lg"
            className="w-full sm:w-auto min-w-[150px]"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <Save className="mr-2 h-4 w-4" />
                Save Schedule
              </>
            )}
          </Button>
        </div>
      </form>
    </div>
  );
}
